### ISSUE TITLE
Select gamemode already has a close/exit button. 

### ISSUE THREAD

**Issue by kavyavandana** [dkim286/cpsc362-proj#11]
The exit button in the select gamemode window is redundant. We already have a close button on the window right? 

the [x] button on the top left corner is meant to close the window and the game. Do we need to have another exit button in the UI? Seems redundant to me. Also the [x] button on the select game mode UI is not working. 

<img width="796" alt="Screen Shot 2021-06-22 at 4 12 38 PM" src="https://user-images.githubusercontent.com/42825107/123011391-1dd40280-d375-11eb-90b0-d940fcefa620.png">

**Comment by dkim286** [comment]
Window decorators are outside of Pygame's control. Some desktop environments don't have those. 

![2021-06-22_16-44](https://user-images.githubusercontent.com/61002244/123013504-e33d8a80-d3b3-11eb-9446-5920278710ec.png)

**Comment by dkim286** [comment]
The decorator x button not working is most likely because the `QUIT` event is not being handled. 

`board.py` has this following lines: 
https://github.com/dkim286/cpsc362-proj/blob/ffe45648bfa8ceab1cd5e1ce5a197e603eb7bc34/ttt/board.py#L70-L73

whereas `cpuselect.py` doesn't have a way to handle `QUIT` events. 

If clicking on x in the select window doesn't work, but works when the game is in progress, then that's the likely culprit.

**Comment by brandonTheProgram** [comment]
Resolved by d88de45
